spring:
  main:
    web-application-type: none
#  datasource:
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 5
#    username: root
#    password: root
#    url: jdbc:postgresql://192.168.100.15:5432/fxbootdb
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true